spring:
  application:
    name: spring-cloud-eureka-2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost
    metadata-map:
      zone: zone-2
  client:
    register-with-eureka: false
    fetch-registry: false
    prefer-same-zone-eureka: true
    region: shanghai
    availability-zones:
      shanghai: zone-1, zone-2
    service-url:
      zone-1: http://localhost:8761/eureka/
      zone-2: http://localhost:8762/eureka/
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 0
