server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-client-server:
      path: /client/**
      serviceId: spring-cloud-client-server
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8888/auth/oauth/token #令牌端点
      user-authorization-uri: http://localhost:8888/auth/oauth/authorize #授权端点
      client-id: spring_cloud_zuul_server #OAuth2客户端ID
      client-secret: secret #OAuth2客户端密钥
    resource:
      jwt:
        key-value: springcloud #使用对称加密方式，默认算法为HS256
      user-info-uri: http://localhost:8888/auth
      prefer-token-info: false