server:
  port: 8080
spring:
  application:
    name: spring-cloud-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meteor1993/SimpleSpringCloudCode.git # git仓库的地址
          search-paths: ch8_1/configFile  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: #Git仓库用户名
          password: #Git仓库密码
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true