server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-host
  cloud:
    gateway:
      routes:
      - id: host_route
        uri: https://github.com
        predicates:
        - Host=**.alpaca.com:${server.port}
