server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-cookie
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: https://github.com
        predicates:
        - Cookie=name, alpaca
