server:
  port: 8000
spring:
  application:
    name: spring-cloud-consumer-server
  rabbitmq:
    host: host
    port: 5672
    username: username
    password: password
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true