server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-filter-addrequestparameter
  cloud:
    gateway:
      routes:
      - id: addrequestparameter_filter
        uri: http://localhost:8081
        predicates:
        - Path= /hello/{segment}
        filters:
        - AddRequestParameter= name, alpaca