server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      routes:
      - id: github_route
        uri: https://github.com
        predicates :
        - Path=/spring-cloud
