server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul-server
  redis:
    host: 101.132.124.125
    password: wsy@123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-client-server:
      path: /client/**
      serviceId: spring-cloud-client-server
  ratelimit:
    key-prefix: springcloud #按粒度拆分的临时变量key前缀
    enabled: true #启用开关
    repository: REDIS #key存储类型，默认是IN_MEMORY本地内存，此外还有多种形式
    behind-proxy: true #表示代理之后
    default-policy-list: #全局限流策略，可单独细化到服务粒度
      - limit: 2 #在一个单位时间窗口的请求数量
        quota: 1 #在一个单位时间窗口的请求时间限制
        refresh-interval: 3 #单位时间窗口
        type: #optional
          - user
          - origin
          - url
          - httpmethod