server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul-server
  redis:
    host: 192.168.0.12
    password: 123456
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-client-server:
      path: /client/**
      serviceId: spring-cloud-client-server
  ratelimit:
    key-prefix: springcloud
    enabled: true
    repository: REDIS
    behind-proxy: true
    add-response-headers: true
    default-policy-list:
      - limit: 2
        quota: 1
        refresh-interval: 3
        type: #optional
          - user
          - origin
          - url
          - httpmethod
    policy-list:
      spring-cloud-client-server:
        - limit: 1
          quota: 1
          refresh-interval: 3
          type: #optional
            - user
            - origin
            - url