server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    spring-cloud-client-server:
      path: /user/**
      serviceId: spring-cloud-user-service
    spring-cloud-auth-service:
      path: /auth/**
      serviceId: spring-cloud-auth-service
  sensitive-headers: token
  ribbon:
    eager-load:
      enabled: true
  host:
    max-per-route-connections: 50
    max-total-connections: 300
    socket-timeout-millis: 5000
    connect-timeout-millis: 5000
  ribbon-isolation-strategy: thread
  thread-pool:
    use-separate-thread-pools: true
    thread-pool-key-prefix: zuul-gateway
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
feign:
  hystrix:
    enabled: true
ribbon:
  ConnectTimeout: 6000
  ReadTimeout: 6000
  MaxAutoRetries: 0 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 0 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: false
hystrix:
  threadpool:
    default:
      coreSize: 20
      maximumSize: 50
      maxQueueSize: -1
      allowMaximumSizeToDivergeFromCoreSize: true
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            interruptOnTimeout: false
            timeoutInMilliseconds: 15000