server:
  port: 8080
spring:
  application:
    name: spring-cloud-feign-log
logging:
  level:
    com:
      springcloud:
        book:
          ch3_2_feign_log:
            service:
              HelloService: debug
