server:
  port: 8000
spring:
  application:
    name: spring-cloud-provider-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true