server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: 139.155.11.128:8848
    gateway:
      routes:
        - id: github_route
          uri: https://github.com
          predicates:
            - Path=/spring-cloud
management:
  endpoints:
    web:
      exposure:
        include: '*'