server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-between
  cloud:
    gateway:
      routes:
      - id: between_route
        uri: https://github.com
        predicates:
        - Between=2019-08-14T11:05:00+08:00[Asia/Shanghai], 2019-08-14T11:10:00+08:00[Asia/Shanghai]
