server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
zuul:
  retryable: true
  ribbon:
    eager-load:
      enabled: true
  routes:
    spring-cloud-client-server:
      path: /client/**
      serviceId: spring-cloud-client-server
ribbon:
  http:
    client:
      enabled: false
  okhttp:
    enabled: true
  #  超时与重试配置
  ConnectTimeout: 3000
  ReadTimeout: 60000
  MaxAutoRetries: 1 #对第一次请求的服务的重试次数
  MaxAutoRetriesNextServer: 1 #要重试的下一个服务的最大数量（不包括第一个服务）
  OkToRetryOnAllOperations: true