server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-filter-stripprefix
  cloud:
    gateway:
      routes:
      - id: stripprefix_filter
        uri: http://github.com
        predicates:
        - Path= /foo/test/{segment}
        filters:
        - StripPrefix=2
