server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-filter-addresponseheader
  cloud:
    gateway:
      routes:
      - id: addresponseheader_filter
        uri: http://www.baidu.com
        predicates:
        - Path= /hello
        filters:
        - AddResponseHeader= X-Response-Foo, alpaca