server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-path
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: https://github.com
        predicates:
        - Path=/spring-cloud/{segment}
