server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-filter-retry
  cloud:
    gateway:
      routes:
      - id: retry_filter
        uri: http://localhost:8081
        predicates:
        - Path= /hello/{segment}
        filters:
        - name: Retry
          args:
            retries: 3
            statuses: BAD_GATEWAY
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG