server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-filter-hystrix
  cloud:
    gateway:
      routes:
      - id: hystrix_filter
        uri: http://localhost:8081
        predicates:
        - Path= /hello/{segment}
        filters:
        - name: Hystrix
          args:
            name: fallbackcmd
            fallbackUri: forward:/fallback
