server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-header
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: https://github.com
        predicates:
        - Header=X-Request-Id, \d+
