server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-remoteaddr
  cloud:
    gateway:
      routes:
      - id: remoteaddr_route
        uri: https://github.com
        predicates:
        - RemoteAddr=127.0.0.1
