server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-filter-rewritepath
  cloud:
    gateway:
      routes:
      - id: rewritepath_filter
        uri: http://github.com
        predicates:
        - Path= /foo/{segment}
        filters:
        - RewritePath= /foo/(?<segment>.*), /$\{segment}
