server:
  port: 8080
spring:
  application:
    name: spring-cloud-gateway-predicate-before
  cloud:
    gateway:
      routes:
      - id: before_route
        uri: https://github.com
        predicates:
        - Before=2019-08-14T10:40:00+08:00[Asia/Shanghai]