server:
  port: 8080
spring:
  application:
    name: spring-cloud-zuul-server
  profiles:
    active: example1
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true